# Generated by Django 2.1.4 on 2018-12-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TemaAluguel', '0002_auto_20181227_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aluguel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='TemaAluguel.Aluguel'),
            preserve_default=False,
        ),
    ]
