# Generated by Django 2.1.4 on 2018-12-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TemaAluguel', '0004_itemtema_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='aluguel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TemaAluguel.Aluguel'),
            preserve_default=False,
        ),
    ]
