# Generated by Django 2.1.4 on 2018-12-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TemaAluguel', '0005_endereco_aluguel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TemaAluguel.Tema'),
            preserve_default=False,
        ),
    ]
