# Generated by Django 2.1.4 on 2018-12-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TemaAluguel', '0006_aluguel_tema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'ordering': ('-data_festa', 'valor_cobrado'), 'verbose_name': 'aluguel', 'verbose_name_plural': 'alugueis'},
        ),
    ]
