# Generated by Django 2.1.4 on 2018-12-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemaAluguel', '0007_auto_20181228_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='hora_termino',
            field=models.TimeField(verbose_name='hora que termina'),
        ),
    ]
